const articles = [
  {
    title: "LoremIpsum1",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et egestas quis ipsum suspendisse ultrices gravida. A condimentum vitae sapien pellentesque habitant. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum. Odio pellentesque diam volutpat commodo sed egestas egestas. Ullamcorper a lacus vestibulum sed arcu non. Nec nam aliquam sem et tortor consequat id porta nibh. Eget gravida cum sociis natoque penatibus et. Quis varius quam quisque id diam. Aliquam ultrices sagittis orci a scelerisque purus. Quis varius quam quisque id diam vel quam. Egestas purus viverra accumsan in. Nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Viverra aliquet eget sit amet tellus cras adipiscing. Ac placerat vestibulum lectus mauris. Diam donec adipiscing tristique risus nec feugiat in fermentum. Sit amet est placerat in. Odio aenean sed adipiscing diam. Velit scelerisque in dictum non. Amet cursus sit amet dictum sit amet justo. Elementum facilisis leo vel fringilla est ullamcorper. Scelerisque varius morbi enim nunc. Elementum tempus egestas sed sed risus. Vitae aliquet nec ullamcorper sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Risus sed vulputate odio ut enim blandit. Iaculis at erat pellentesque adipiscing commodo. Sit amet dictum sit amet justo donec enim diam vulputate.",
  },
  {
    title: "LoremIpsum2",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et egestas quis ipsum suspendisse ultrices gravida. A condimentum vitae sapien pellentesque habitant. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum. Odio pellentesque diam volutpat commodo sed egestas egestas. Ullamcorper a lacus vestibulum sed arcu non. Nec nam aliquam sem et tortor consequat id porta nibh. Eget gravida cum sociis natoque penatibus et. Quis varius quam quisque id diam. Aliquam ultrices sagittis orci a scelerisque purus. Quis varius quam quisque id diam vel quam. Egestas purus viverra accumsan in. Nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Viverra aliquet eget sit amet tellus cras adipiscing. Ac placerat vestibulum lectus mauris. Diam donec adipiscing tristique risus nec feugiat in fermentum. Sit amet est placerat in. Odio aenean sed adipiscing diam. Velit scelerisque in dictum non. Amet cursus sit amet dictum sit amet justo. Elementum facilisis leo vel fringilla est ullamcorper. Scelerisque varius morbi enim nunc. Elementum tempus egestas sed sed risus. Vitae aliquet nec ullamcorper sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Risus sed vulputate odio ut enim blandit. Iaculis at erat pellentesque adipiscing commodo. Sit amet dictum sit amet justo donec enim diam vulputate.",
  },
  {
    title: "LoremIpsum3",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et egestas quis ipsum suspendisse ultrices gravida. A condimentum vitae sapien pellentesque habitant. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum. Odio pellentesque diam volutpat commodo sed egestas egestas. Ullamcorper a lacus vestibulum sed arcu non. Nec nam aliquam sem et tortor consequat id porta nibh. Eget gravida cum sociis natoque penatibus et. Quis varius quam quisque id diam. Aliquam ultrices sagittis orci a scelerisque purus. Quis varius quam quisque id diam vel quam. Egestas purus viverra accumsan in. Nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Viverra aliquet eget sit amet tellus cras adipiscing. Ac placerat vestibulum lectus mauris. Diam donec adipiscing tristique risus nec feugiat in fermentum. Sit amet est placerat in. Odio aenean sed adipiscing diam. Velit scelerisque in dictum non. Amet cursus sit amet dictum sit amet justo. Elementum facilisis leo vel fringilla est ullamcorper. Scelerisque varius morbi enim nunc. Elementum tempus egestas sed sed risus. Vitae aliquet nec ullamcorper sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Risus sed vulputate odio ut enim blandit. Iaculis at erat pellentesque adipiscing commodo. Sit amet dictum sit amet justo donec enim diam vulputate.",
  },
  {
    title: "LoremIpsum4",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et egestas quis ipsum suspendisse ultrices gravida. A condimentum vitae sapien pellentesque habitant. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum. Odio pellentesque diam volutpat commodo sed egestas egestas. Ullamcorper a lacus vestibulum sed arcu non. Nec nam aliquam sem et tortor consequat id porta nibh. Eget gravida cum sociis natoque penatibus et. Quis varius quam quisque id diam. Aliquam ultrices sagittis orci a scelerisque purus. Quis varius quam quisque id diam vel quam. Egestas purus viverra accumsan in. Nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Viverra aliquet eget sit amet tellus cras adipiscing. Ac placerat vestibulum lectus mauris. Diam donec adipiscing tristique risus nec feugiat in fermentum. Sit amet est placerat in. Odio aenean sed adipiscing diam. Velit scelerisque in dictum non. Amet cursus sit amet dictum sit amet justo. Elementum facilisis leo vel fringilla est ullamcorper. Scelerisque varius morbi enim nunc. Elementum tempus egestas sed sed risus. Vitae aliquet nec ullamcorper sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Risus sed vulputate odio ut enim blandit. Iaculis at erat pellentesque adipiscing commodo. Sit amet dictum sit amet justo donec enim diam vulputate.",
  },
  {
    title: "LoremIpsum5",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et egestas quis ipsum suspendisse ultrices gravida. A condimentum vitae sapien pellentesque habitant. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum. Odio pellentesque diam volutpat commodo sed egestas egestas. Ullamcorper a lacus vestibulum sed arcu non. Nec nam aliquam sem et tortor consequat id porta nibh. Eget gravida cum sociis natoque penatibus et. Quis varius quam quisque id diam. Aliquam ultrices sagittis orci a scelerisque purus. Quis varius quam quisque id diam vel quam. Egestas purus viverra accumsan in. Nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Viverra aliquet eget sit amet tellus cras adipiscing. Ac placerat vestibulum lectus mauris. Diam donec adipiscing tristique risus nec feugiat in fermentum. Sit amet est placerat in. Odio aenean sed adipiscing diam. Velit scelerisque in dictum non. Amet cursus sit amet dictum sit amet justo. Elementum facilisis leo vel fringilla est ullamcorper. Scelerisque varius morbi enim nunc. Elementum tempus egestas sed sed risus. Vitae aliquet nec ullamcorper sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Risus sed vulputate odio ut enim blandit. Iaculis at erat pellentesque adipiscing commodo. Sit amet dictum sit amet justo donec enim diam vulputate.",
  },
  {
    title: "LoremIpsum6",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et egestas quis ipsum suspendisse ultrices gravida. A condimentum vitae sapien pellentesque habitant. Mauris nunc congue nisi vitae suscipit tellus mauris. Pulvinar neque laoreet suspendisse interdum. Odio pellentesque diam volutpat commodo sed egestas egestas. Ullamcorper a lacus vestibulum sed arcu non. Nec nam aliquam sem et tortor consequat id porta nibh. Eget gravida cum sociis natoque penatibus et. Quis varius quam quisque id diam. Aliquam ultrices sagittis orci a scelerisque purus. Quis varius quam quisque id diam vel quam. Egestas purus viverra accumsan in. Nisi est sit amet facilisis. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Viverra aliquet eget sit amet tellus cras adipiscing. Ac placerat vestibulum lectus mauris. Diam donec adipiscing tristique risus nec feugiat in fermentum. Sit amet est placerat in. Odio aenean sed adipiscing diam. Velit scelerisque in dictum non. Amet cursus sit amet dictum sit amet justo. Elementum facilisis leo vel fringilla est ullamcorper. Scelerisque varius morbi enim nunc. Elementum tempus egestas sed sed risus. Vitae aliquet nec ullamcorper sit. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Risus sed vulputate odio ut enim blandit. Iaculis at erat pellentesque adipiscing commodo. Sit amet dictum sit amet justo donec enim diam vulputate.",
  },
];

export default articles;